// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6FEvENDb_I35twG2yEMhVPwUt3mwOghg',
    appId: '1:384686075525:web:f23149dd477c14f25b83ec',
    messagingSenderId: '384686075525',
    projectId: 'savermax-f0232',
    authDomain: 'savermax-f0232.firebaseapp.com',
    storageBucket: 'savermax-f0232.appspot.com',
    measurementId: 'G-6DFVT6989E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9UhQ5KZyUm6jdRuBCaTSeuFfvfqFmAOc',
    appId: '1:832475498084:android:f594be37df3289aab74171',
    messagingSenderId: '832475498084',
    projectId: 'savermax-8754d',
    storageBucket: 'savermax-8754d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApLDEQ4Z5eDkBU4TMTbKz9DErcMT1v45c',
    appId: '1:832475498084:ios:d47b210147a7c2a4b74171',
    messagingSenderId: '832475498084',
    projectId: 'savermax-8754d',
    storageBucket: 'savermax-8754d.appspot.com',
    iosBundleId: 'com.example.whatsappStatusSaver',
  );

}